source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 7.0

target 'mxAsTubeiPad', :exclusive => true do
  # pod 'Reveal-iOS-SDK'

  # ________________open projects___________________
  pod "GGTabBar", :path => "../dependencies/lib/GGTabBar"
  pod "YKMediaPlayerKit", :path => "../dependencies/lib/YKMediaPlayerKit"
  pod "XCDYouTubeKit", :path => "../dependencies/lib/XCDYouTubeKit"
  pod "STCollapseTableView", :path => "../dependencies/lib/STCollapseTableView"
  pod "SWRevealViewController", :path => "../dependencies/lib/SWRevealViewController"

  pod "AFNetworking", :path => "../dependencies/lib/AFNetworking"
  pod "KRLCollectionViewGridLayout", :path => "../dependencies/lib/KRLCollectionViewGridLayout"
  pod "AsyncDisplayKit", :path => "../dependencies/lib/AsyncDisplayKit"

  pod "ISMemoryCache", :path => "../dependencies/lib/Cache/ISMemoryCache"
  pod "SDWebImage", :path => "../dependencies/lib/Cache/SDWebImage"


  pod "YouTubeAPI3-Objective-C-wrapper", :path => "../dependencies/lib/google-api-client/YouTubeAPI3-Objective-C-wrapper"
  pod "Google-API-Client-local", :path => "../dependencies/lib/google-api-client/Google-API-Client-local"
  pod "gtm-http-fetcher-local", :path => "../dependencies/lib/google-api-client/gtm-http-fetcher-local"
  pod "gtm-oauth2-local", :path => "../dependencies/lib/google-api-client/gtm-oauth2-local"



  # ________________collect common library___________________
  pod "IOS_Collection_Code", :path => "../dependencies/collect/IOS_Collection_Code"

  # ________________Project layers___________________
  pod "Business-Logic-Layer", :path => "../dependencies/layers/Business-Logic-Layer"
  pod "google-api-services-youtube", :path => "../dependencies/layers/google-api-services-youtube"

  # ________________Projects for iPad___________________
  # ________________module Projects___________________
  pod "VideoWatchDetailViewControlleriPad", :path => "../dependencies/ipad/VideoWatchDetailViewControlleriPad"
  pod "Youtube_ChannelPage_Controller", :path => "../dependencies/ipad/Youtube_ChannelPage_Controller"
  pod "youtube_slide_menu", :path => "../dependencies/ipad/youtube_slide_menu"
  pod "YoutubeCollectionView", :path => "../dependencies/ipad/YoutubeCollectionView"

end
